### ISSUE TITLE
Log AmazonS3Exception.

### ISSUE THREAD

**Issue by sirvon** [OneCodeLabs/S3UploadService#4]
[should log exception here, so consumers can see the exception message](https://github.com/OneCodeLabs/S3UploadService/blob/master/s3/src/main/java/com/onecode/s3/service/S3UploadService.java#L105)

```java
        try {
            upload.waitForCompletion();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (AmazonS3Exception s3e) {
            // Possible Bad Digest. Retry
            Log.w(TAG, "AmazonS3Exception. retrying.");
        }
```
should include....
```java
Log.d(TAG,s3e.toString)
```

at the least, IMHO

**Comment by goodengineer** [comment]
@sirvon Thanks for your suggestion! This is now added in #5
